apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus
spec:
  jobName: prometheus
  honorTimestamps: true
  scrapeInterval: 15s
  scrapeTimeout: 5s
  metricsPath: /metrics
  scheme: HTTP
  staticConfigs:
    - targets:
        - localhost:9090
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: gnmic
spec:
  jobName: gnmic
  staticConfigs:
    - targets:
        - gnmic-ingestor.svc.cluster.local:7890
        - gnmic-emitter.svc.cluster.local:7890
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nats
spec:
  jobName: nats
  staticConfigs:
    - targets:
        - nats-exporter.svc.cluster.local:7777