apiVersion: v1
kind: Service
metadata:
  labels:
    service: gnmic-emitter
  name: gnmic-emitter
spec:
  ports:
    - name: "9806"
      port: 9806
      targetPort: 9804
  selector:
    service: gnmic-emitter
