apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: gnmic-ingestor
  name: gnmic-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gnmic-ingestor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: gnmic-ingestor
    spec:
      containers:
        - args:
            - --config
            - /app/gnmic.yaml
            - --log
            - subscribe
          image: ghcr.io/openconfig/gnmic:0.42.0
          name: gnmic-ingestor
          ports:
            - containerPort: 9804
              protocol: TCP
          volumeMounts:
            - mountPath: /app/gnmic.yaml
              name: gnmic-ingestor-cm0
              readOnly: true
              subPath: gnmic.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: gnmic-ingestor.yaml
                path: gnmic.yaml
            name: gnmic-ingestor-cm0
          name: gnmic-ingestor-cm0
