apiVersion: v1
data:
  gnmic-ingestor.yaml: {{- .Values.gnmic.ingestor.config | toYaml | indent 2 }}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    service: gnmic-ingestor
  name: gnmic-ingestor-cm0
  namespace: gnp-stack
