{{- with .Values.goflow -}}
{{- if .enabled -}}
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.3/service.json
apiVersion: v1
kind: Service
metadata:
  name: goflow2-udp-netflow
spec:
  type: LoadBalancer
  selector:
    app: goflow2
  ports:
    - name: netflow
      protocol: UDP
      port: 2055
      targetPort: 2055
{{- end -}}
{{- end -}}