apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: docker.io/clickhouse:25.9.4
          ports:
            - containerPort: 8123
          env:
            - name: CLICKHOUSE_USER
              value: grafana
          command: {{- .Values.clickhouse.command | toYaml | indent 2 }}
          volumeMounts:
            - mountPath: /mnt/clickhouse-config/
              name: cfgmap
            - mountPath: /var/lib/clickhouse/store
              name: clickhouse-store
      volumes:
        - name: cfgmap
          configMap:
            name: clickhouse-config
        - name: clickhouse-store
          persistentVolumeClaim:
            claimName: clickhouse-store
