apiVersion: v1
data:
  gnmic-emitter.yaml: {{- .Values.gnmic.ingestor.config | toYaml | indent 2 }}
kind: ConfigMap
metadata:
  labels:
    service: gnmic-emitter
  name: gnmic-emitter-cm0
  namespace: gnp-stack
